huh_encore:
  encore:
    entries:
      - { name: "contao-pwa-bundle", requiresCss: false, head: false, file: "vendor/heimrichhannot/contao-pwa-bundle/src/Resources/assets/js/contaoPwaBundle.es6.js"}
    legacy:
      js:
        - huh.pwa.bundle