huh_encore:
  js_entries:
    - name: "contao-pwa-bundle"
      requires_css: false
      head: false
      file: "vendor/heimrichhannot/contao-pwa-bundle/src/Resources/assets/js/contao-pwa-bundle.js"
  unset_global_keys:
    js:
      - "huh.pwa.bundle"