services:
  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - ["setFramework", ["@contao.framework"]]
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

  HeimrichHannot\ContaoPwaBundle\:
    resource: '../../{Command,Controller,DataContainer,EventListener}/*'
    public: true
    autowire: true
    autoconfigure: true

  huh.pwa.listener.commandscheduler:
    class: HeimrichHannot\ContaoPwaBundle\EventListener\CronjobListener
    public: true
    arguments:
      ['@huh.pwa.sender.pushnotification', '@logger']
  HeimrichHannot\ContaoPwaBundle\EventListener\CronjobListener: '@huh.pwa.listener.commandscheduler'

  huh.pwalist.choice.template.item:
    class: HeimrichHannot\ContaoPwaBundle\DataContainer\ContentContainer
    public: true
    autowire: true
  HeimrichHannot\ContaoPwaBundle\DataContainer\ContentContainer: '@huh.pwalist.choice.template.item'

# DataContainer

  huh.pwa.datacontainer.pwapushnotification:
    class: HeimrichHannot\ContaoPwaBundle\DataContainer\PwaPushNotificationContainer
    public: true
    autowire: true
  HeimrichHannot\ContaoPwaBundle\DataContainer\PwaPushNotificationContainer: '@huh.pwa.datacontainer.pwapushnotification'

  huh.pwa.datacontainer.pwaconfigurations:
    class: HeimrichHannot\ContaoPwaBundle\DataContainer\PwaConfigurationContainer
    public: true
    autowire: true
  HeimrichHannot\ContaoPwaBundle\DataContainer\PwaConfigurationContainer: '@huh.pwa.datacontainer.pwaconfigurations'

  huh.pwa.datacontainer.pwasubscribers:
    class: HeimrichHannot\ContaoPwaBundle\DataContainer\PwaPushSubscriberContainer
    public: true
    autowire: true
  HeimrichHannot\ContaoPwaBundle\DataContainer\PwaPushSubscriberContainer: '@huh.pwa.datacontainer.pwasubscribers'

  # Generators

  huh.pwa.generator.manifest:
    class: HeimrichHannot\ContaoPwaBundle\Generator\ManifestGenerator
    public: true
    arguments:
      ['@service_container', '@huh.pwa.generator.icon']
  HeimrichHannot\ContaoPwaBundle\Generator\ManifestGenerator: "@huh.pwa.generator.manifest"

  huh.pwa.generator.icon:
    class: HeimrichHannot\ContaoPwaBundle\Generator\ManifestIconGenerator
    public: true
    arguments:
      ['@contao.image.image_factory', '@contao.image.resizer', '@service_container']
  HeimrichHannot\ContaoPwaBundle\Generator\ManifestIconGenerator: "@huh.pwa.generator.icon"

  huh.pwa.generator.serviceworker:
    class: HeimrichHannot\ContaoPwaBundle\Generator\ServiceWorkerGenerator
    public: true
    arguments:
      ['%contao.web_dir%', '@twig', '@logger']
  HeimrichHannot\ContaoPwaBundle\Generator\ServiceWorkerGenerator: "@huh.pwa.generator.serviceworker"

  huh.pwa.generator.configurationfile:
    class: HeimrichHannot\ContaoPwaBundle\Generator\ConfigurationFileGenerator
    public: true
    arguments:
      ['@router.default', '%contao.web_dir%', '%huh_pwa%', '@translator']
  HeimrichHannot\ContaoPwaBundle\Generator\ConfigurationFileGenerator: "@huh.pwa.generator.configurationfile"

  # Header Tags

  huh.head.tag.pwa.link_manifest:
    class: HeimrichHannot\ContaoPwaBundle\HeaderTag\ManifestLinkTag
    public: true
    arguments:
      ['@huh.head.tag_manager']
  HeimrichHannot\ContaoPwaBundle\HeaderTag\ManifestLinkTag: "@huh.head.tag.pwa.link_manifest"

  huh.head.tag.pwa.meta_themecolor:
    class: HeimrichHannot\ContaoPwaBundle\HeaderTag\ThemeColorMetaTag
    public: true
    arguments:
      ['@huh.head.tag_manager']
  HeimrichHannot\ContaoPwaBundle\HeaderTag\ThemeColorMetaTag: "@huh.head.tag.pwa.meta_themecolor"

  huh.head.tag.pwa.script:
    class: HeimrichHannot\ContaoPwaBundle\HeaderTag\PwaHeadScriptTags
    public: true
    arguments:
      ['@huh.head.tag_manager']
  HeimrichHannot\ContaoPwaBundle\HeaderTag\PwaHeadScriptTags: "@huh.head.tag.pwa.script"

# Sender

  huh.pwa.sender.pushnotification:
    class: HeimrichHannot\ContaoPwaBundle\Sender\PushNotificationSender
    public: true
    arguments:
      ['%huh_pwa%', '@huh.pwa.datacontainer.pwapushnotification', '@huh.utils.container']
  HeimrichHannot\ContaoPwaBundle\Sender\PushNotificationSender: '@huh.pwa.sender.pushnotification'