services:

  huh.pwa.listener.hook:
    class: HeimrichHannot\ContaoPwaBundle\EventListener\HookListener
    public: true
    autowire: true
  huh.pwa.listener.usernavigation:
    class: HeimrichHannot\ContaoPwaBundle\EventListener\UserNavigationListener
    arguments:
      ['@request_stack', '@router']
  huh.pwa.listener.commandscheduler:
    class: HeimrichHannot\ContaoPwaBundle\EventListener\CronjobListener
    arguments:
      ['@huh.pwa.sender.pushnotification']
  huh.pwa.datacontainer.page:
    class: HeimrichHannot\ContaoPwaBundle\DataContainer\PageContainer
    public: true
    autowire: true
  huh.pwa.datacontainer.pwapushnotification:
    class: HeimrichHannot\ContaoPwaBundle\DataContainer\PwaPushNotificationContainer
    public: true
    autowire: true

# Generators

  huh.pwa.generator.manifest:
    class: HeimrichHannot\ContaoPwaBundle\Generator\ManifestGenerator
    public: true
    arguments:
      ['@service_container', '@huh.pwa.generator.icon']
  HeimrichHannot\ContaoPwaBundle\Generator\ManifestGenerator: "@huh.pwa.generator.manifest"
  huh.pwa.generator.icon:
    class: HeimrichHannot\ContaoPwaBundle\Generator\ManifestIconGenerator
    public: true
    arguments:
      ['@contao.image.image_factory', '@contao.image.resizer', '@service_container']
  HeimrichHannot\ContaoPwaBundle\Generator\ManifestIconGenerator: "@huh.pwa.generator.icon"

# Header Tags

  huh.head.tag.pwa.link_manifest:
    class: HeimrichHannot\ContaoPwaBundle\HeaderTag\ManifestLinkTag
    public: true
    arguments:
      ['@huh.head.tag_manager']
  HeimrichHannot\ContaoPwaBundle\HeaderTag\ManifestLinkTag: "@huh.head.tag.pwa.link_manifest"
  huh.head.tag.pwa.meta_themecolor:
    class: HeimrichHannot\ContaoPwaBundle\HeaderTag\ThemeColorMetaTag
    public: true
    arguments:
      ['@huh.head.tag_manager']
  HeimrichHannot\ContaoPwaBundle\HeaderTag\ThemeColorMetaTag: "@huh.head.tag.pwa.meta_themecolor"

# Sender

  huh.pwa.sender.pushnotification:
    class: HeimrichHannot\ContaoPwaBundle\Sender\PushNotificationSender
    public: true
    arguments:
      ['%huh.pwa%']